[plugin]
id = "io.tsukasa.millennium.personal-calendar"
name = "Personal Calendar"
version = "0.0.2"
author = "tsukasa"
description = "Adds a link to Your Personal Calendar between Discovery Queue and Wishlist in the Store menu."

[assets]
resources = ["LICENSE"]

[backend]
entry = "backend/main.lua"
sources = ["backend/**/*.lua"]

[compiler]
output_path = "dist/io.tsukasa.millennium.personal-calendar.star"

[dev]
auto_restart = true
reload_steamui_when = "backend"

[patches]
debug = false
